import type { Page, Request } from '@playwright/test'
import { test, expect } from './fixtures'
import { serializeMention } from '../shared/mentions'

async function enter(page: Page, email: string) {
  await page.goto('/')
  await page.getByRole('textbox', { name: '邮箱地址' }).fill(email)
  await page.getByRole('button', { name: '进入我的日历' }).click()
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
}

async function switchSpace(page: Page, email: string) {
  await page.getByRole('button', { name: /我的空间/ }).click()
  await page.getByRole('textbox', { name: '邮箱地址' }).fill(email)
  await page.getByRole('button', { name: '切换数据空间' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
}

async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
}

async function editSidebarProject(page: Page, name: string) {
  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: `项目操作 ${name}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '编辑', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '编辑项目', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: '项目名称' })).toBeFocused()
}

test('单事项卡片与编辑弹窗打开独立打印页', async ({ page, space, otherSpace }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('打印项目')
  const other = await space.project('其他项目')
  const referenced = await space.entry(other.id, '引用目标', null)
  const description = `**完整描述**\n\n${'较长的正文用于检查打印分页。'.repeat(80)}\n\n${serializeMention({ id: referenced, title: '引用目标' })}`
  const id = await space.entry(project.id, '打印事项', '2026-09-13', [referenced], description)
  await space.entry(other.id, '别的事项', '2026-09-13', [id])
  expect((await space.api.patch(`/api/entries/${id}`, { data: { completed: true } })).ok()).toBe(true)
  await enter(page, space.email)
  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: /^打印项目/ }).click()
  const card = page.locator(`#entry-${id}`)
  await expect(card).toBeVisible()
  const popupPromise = page.waitForEvent('popup')
  await card.getByRole('button', { name: '导出事项 打印事项' }).click()
  const printPage = await popupPromise
  await expect(printPage).toHaveURL(new RegExp(`\\?printEntry=${id}$`))
  await expect(printPage.getByRole('heading', { name: '打印事项' })).toBeVisible()
  const sheet = printPage.locator('.print-sheet')
  await expect(sheet).toContainText('打印项目')
  await expect(sheet).toContainText('2026-09-13')
  await expect(sheet).toContainText('已完成')
  await expect(sheet.locator('.entry-description strong')).toHaveText('完整描述')
  await expect(sheet.locator('.entry-mention')).toHaveText('@引用目标')
  await expect(sheet).toContainText('@别的事项')
  await expect(sheet.locator('.entry-description')).toContainText('较长的正文用于检查打印分页。'.repeat(80))
  await noOverflow(printPage)
  await printPage.screenshot({ path: testInfo.outputPath('entry-print.png'), fullPage: true, animations: 'disabled' })
  await printPage.emulateMedia({ media: 'print' })
  await expect(printPage.locator('.print-toolbar')).toHaveCSS('display', 'none')
  await expect(sheet).toHaveCSS('border-top-width', '0px')
  const pdf = await printPage.pdf({ format: 'A4', printBackground: true })
  expect(pdf.subarray(0, 5).toString()).toBe('%PDF-')
  await printPage.emulateMedia({ media: 'screen' })
  await printPage.evaluate(() => { window.print = () => { document.documentElement.dataset.printCalled = 'true' } })
  await printPage.getByRole('button', { name: '打印 / 保存为 PDF' }).click()
  await expect(printPage.locator('html')).toHaveAttribute('data-print-called', 'true')
  await printPage.reload()
  await expect(printPage.getByRole('heading', { name: '打印事项' })).toBeVisible()

  await card.getByRole('button', { name: '编辑事项 打印事项' }).click()
  await expect(page.getByRole('button', { name: '导出已保存事项' })).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('entry-editor-actions.png'), animations: 'disabled' })
  await page.getByRole('textbox', { name: '事项标题' }).fill('未保存的标题')
  const editorPopupPromise = page.waitForEvent('popup')
  await page.getByRole('button', { name: '导出已保存事项' }).click()
  const editorPrint = await editorPopupPromise
  await expect(editorPrint.getByRole('heading', { name: '打印事项' })).toBeVisible()
  await expect(editorPrint.getByText('未保存的标题')).toHaveCount(0)
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await editorPrint.close()

  await page.getByRole('combobox', { name: '工作台视图' }).click()
  await page.getByRole('option', { name: '项目总览', exact: true }).click()
  await page.getByRole('button', { name: '已完成 1' }).click()
  const overviewPopupPromise = page.waitForEvent('popup')
  await page.locator(`#entry-${id}`).getByRole('button', { name: '导出事项 打印事项' }).click()
  const overviewPrint = await overviewPopupPromise
  await expect(overviewPrint.getByRole('heading', { name: '打印事项' })).toBeVisible()
  await overviewPrint.close()

  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: /^其他项目/ }).click()
  const undatedPopupPromise = page.waitForEvent('popup')
  await page.locator(`#entry-${referenced}`).getByRole('button', { name: '导出事项 引用目标' }).click()
  const undatedPrint = await undatedPopupPromise
  await expect(undatedPrint.getByRole('heading', { name: '引用目标' })).toBeVisible()
  await expect(undatedPrint.locator('.print-meta')).toContainText('未设日期')
  await expect(undatedPrint.locator('.print-sheet')).not.toContainText('完整描述')
  await undatedPrint.close()

  await printPage.evaluate(email => localStorage.setItem('agenda:email', email), otherSpace.email)
  await printPage.reload()
  await expect(printPage.getByRole('heading', { name: '找不到这个事项' })).toBeVisible()
  await printPage.close()
})

test('统一项目排序弹窗、菜单、刷新、视图同步与保存失败', async ({ page, space, isMobile }, testInfo) => {
  const a = await space.project('甲')
  const b = await space.project('乙')
  const c = await space.project('丙')
  await enter(page, space.email)
  const names = page.locator('.project-nav-row .truncate')
  await expect(names).toHaveText(['甲', '乙', '丙'])
  await expect(page.locator('.project-nav-row .project-drag-handle')).toHaveCount(0)
  const orderButton = page.getByRole('button', { name: '编辑项目排序' })
  await expect(orderButton).toBeEnabled()
  let releaseSave!: () => void
  let releaseRefresh!: () => void
  let refreshing = false
  const saveGate = new Promise<void>(resolve => { releaseSave = resolve })
  const refreshGate = new Promise<void>(resolve => { releaseRefresh = resolve })
  await page.route('**/api/projects/order', async route => { await saveGate; await route.continue() })
  await page.route('**/api/agenda', async route => { refreshing = true; await refreshGate; await route.continue() })
  await page.getByRole('button', { name: '项目操作 甲', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '上移', exact: true })).toBeDisabled()
  await page.getByRole('menuitem', { name: '下移', exact: true }).click()
  const pending = page.getByRole('status').filter({ hasText: '正在调整项目顺序' })
  await expect(pending).toBeVisible()
  await expect(orderButton).toBeDisabled()
  await expect(page.getByRole('button', { name: '项目操作 甲', exact: true })).toBeDisabled()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('project-sort-pending.png') })
  releaseSave()
  await expect.poll(() => refreshing).toBe(true)
  await expect(pending).toBeVisible()
  releaseRefresh()
  await expect(names).toHaveText(['乙', '甲', '丙'])
  await expect(pending).toBeHidden()
  await page.unroute('**/api/projects/order')
  await page.unroute('**/api/agenda')
  await expect(page.locator('.sync-button')).toBeEnabled()
  await page.getByRole('button', { name: '项目操作 丙', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '下移', exact: true })).toBeDisabled()
  await page.keyboard.press('Escape')

  await orderButton.click()
  const dialog = page.getByRole('dialog', { name: '调整项目顺序' })
  const orderRows = dialog.locator('.project-order-row')
  await expect(orderRows).toContainText(['乙', '甲', '丙'])
  await dialog.getByRole('button', { name: /调整 乙 的顺序/ }).focus()
  await page.keyboard.press('ArrowDown')
  await expect(orderRows).toContainText(['甲', '乙', '丙'])
  await expect(names).toHaveText(['乙', '甲', '丙'])
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await expect(dialog).toBeHidden()
  await orderButton.click()
  await expect(orderRows).toContainText(['乙', '甲', '丙'])
  const handle = dialog.getByRole('button', { name: /调整 乙 的顺序/ })
  const start = (await handle.boundingBox())!
  const target = (await orderRows.last().boundingBox())!
  const x = start.x + start.width / 2
  const y = start.y + start.height / 2
  const endY = target.y + target.height - 4
  if (isMobile) {
    const session = await page.context().newCDPSession(page)
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y: endY }] })
    await expect(dialog.locator('.project-order-dragging')).toHaveCount(1)
    await page.screenshot({ path: testInfo.outputPath('project-sort-drag.png') })
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await session.detach()
  } else {
    await page.mouse.move(x, y)
    await page.mouse.down()
    await page.mouse.move(x, endY, { steps: 8 })
    await expect(dialog.locator('.project-order-dragging')).toHaveCount(1)
    await page.screenshot({ path: testInfo.outputPath('project-sort-drag.png') })
    await page.mouse.up()
  }
  await expect(orderRows).toContainText(['甲', '丙', '乙'])
  await expect(names).toHaveText(['乙', '甲', '丙'])
  await page.screenshot({ path: testInfo.outputPath('project-sort-editor.png'), animations: 'disabled' })
  let releaseEditorSave!: () => void
  const editorSaveGate = new Promise<void>(resolve => { releaseEditorSave = resolve })
  await page.route('**/api/projects/order', async route => { await editorSaveGate; await route.continue() })
  await dialog.getByRole('button', { name: '保存排序' }).click()
  await expect(dialog.getByRole('button', { name: '保存中…' })).toBeDisabled()
  await expect(dialog.getByRole('button', { name: '关闭弹窗' })).toBeDisabled()
  await expect(pending).toBeVisible()
  releaseEditorSave()
  await expect(dialog).toBeHidden()
  await page.unroute('**/api/projects/order')
  await expect(names).toHaveText(['甲', '丙', '乙'])
  expect((await space.agenda()).projects.map(project => project.id)).toEqual([a.id, c.id, b.id])
  await expect(page.getByRole('button', { name: /^全部项目/ })).toHaveAttribute('aria-pressed', 'true')
  await orderButton.click()
  await dialog.getByRole('button', { name: /调整 丙 的顺序/ }).focus()
  await page.keyboard.press('ArrowUp')
  await expect(orderRows).toContainText(['丙', '甲', '乙'])
  await dialog.getByRole('button', { name: '保存排序' }).click()
  await expect(names).toHaveText(['丙', '甲', '乙'])
  await page.getByRole('button', { name: '项目操作 丙', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '上移', exact: true })).toBeDisabled()
  await page.getByRole('menuitem', { name: '下移', exact: true }).click()
  await expect(names).toHaveText(['甲', '丙', '乙'])
  await page.reload()
  await expect(names).toHaveText(['甲', '丙', '乙'])
  await page.getByRole('combobox', { name: '工作台视图' }).click()
  await page.getByRole('option', { name: '项目总览', exact: true }).click()
  await expect(page.locator('.overview-project h3')).toHaveText(['甲', '丙', '乙'])
  await page.getByRole('button', { name: '为 甲 添加事项', exact: true }).click()
  await expect(page.getByLabel('所属项目').locator('option')).toHaveText(['甲', '丙', '乙'])
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.route('**/api/projects/order', route => route.fulfill({ status: 503, json: { error: '排序保存失败' } }))
  await orderButton.click()
  await dialog.getByRole('button', { name: /调整 甲 的顺序/ }).focus()
  await page.keyboard.press('ArrowDown')
  await dialog.getByRole('button', { name: '保存排序' }).click()
  await expect(dialog.getByRole('alert')).toContainText('排序保存失败')
  await expect(orderRows).toContainText(['丙', '甲', '乙'])
  await expect(names).toHaveText(['甲', '丙', '乙'])
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '项目操作 甲', exact: true }).click()
  await page.getByRole('menuitem', { name: '下移', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('排序保存失败')
  await expect(pending).toBeHidden()
  await expect(names).toHaveText(['甲', '丙', '乙'])
  await noOverflow(page)
})

test('邮箱进入、项目和事项编辑、完成、双向引用跳转与删除', async ({ page, space, otherSpace, baseURL, isMobile }, testInfo) => {
  test.setTimeout(60_000)
  const errors: string[] = []
  const apiRequests: Request[] = []
  await page.context().addCookies([{ name: 'agenda-test-session', value: 'same-origin', url: baseURL!, httpOnly: true, sameSite: 'Lax' }])
  page.on('request', request => {
    if (new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request)
  })
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '项目日历', exact: true })).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('welcome.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('textbox', { name: '邮箱地址' }).fill(space.email.toUpperCase())
  await page.getByRole('button', { name: '进入我的日历' }).click()
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
  await expect(page.getByRole('heading', { name: '(空)', exact: true })).toBeVisible()
  await expect(page.locator('.sync-button')).toHaveText('已与云端同步 · 12:00:00')
  if (isMobile) await page.getByRole('button', { name: '月', exact: true }).click()

  for (const [name, color] of [['个人网站', '颜色 1'], ['阅读计划', '颜色 2']] as const) {
    await page.getByRole('button', { name: '新建项目', exact: true }).click()
    await page.getByRole('textbox', { name: '项目名称' }).fill(name)
    await page.getByRole('button', { name: color, exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '创建项目', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
  }
  await editSidebarProject(page, '个人网站')
  await page.getByRole('textbox', { name: '项目名称' }).fill('网站计划')
  await page.getByLabel('RGB R', { exact: true }).fill('18')
  await page.getByLabel('RGB G', { exact: true }).fill('171')
  await page.getByLabel('RGB B', { exact: true }).fill('239')
  await expect(page.locator('.color-preview')).toHaveCSS('background-color', 'rgb(18, 171, 239)')
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('project-rgb.png'), animations: 'disabled' })
  await page.getByRole('button', { name: '保存项目' }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  expect((await space.agenda()).projects.find(project => project.name === '网站计划')?.color).toBe('#12ABEF')
  await editSidebarProject(page, '网站计划')
  await expect(page.getByLabel('RGB R', { exact: true })).toHaveValue('18')
  await expect(page.getByLabel('RGB G', { exact: true })).toHaveValue('171')
  await expect(page.getByLabel('RGB B', { exact: true })).toHaveValue('239')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.locator('.add-main').click()
  await page.getByRole('textbox', { name: '事项标题' }).fill('设计首页')
  await page.getByLabel('所属项目').selectOption({ label: '网站计划' })
  await page.getByRole('dialog').getByRole('button', { name: '添加事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.entry-title')).toHaveText('设计首页')
  expect((await space.agenda()).entries[0]?.description).toBe('')
  await page.getByRole('button', { name: '标为完成：设计首页', exact: true }).click()
  await expect(page.getByRole('button', { name: '标为未完成：设计首页', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.summary-counts')).toHaveText(/总数\s*1\s*\/\s*未完成\s*0/)

  await page.getByRole('button', { name: '下个月', exact: true }).click()
  await page.getByRole('button', { name: '选择 2026-10-02', exact: true }).click()
  await page.locator('.add-main').click()
  await page.getByRole('textbox', { name: '事项标题' }).fill('整理设计灵感')
  await page.getByLabel('所属项目').selectOption({ label: '阅读计划' })
  await expect(page.getByLabel('记录日期')).toHaveText('2026-10-02')
  await page.getByLabel('记录日期').click()
  await expect(page.getByRole('dialog', { name: '记录日期', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '2026.10', exact: true })).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('date-picker-editor.png'), animations: 'disabled' })
  await page.getByRole('button', { name: /2026年10月3日/ }).click()
  await expect(page.getByLabel('记录日期')).toHaveText('2026-10-03')
  await page.getByLabel('记录日期').click()
  await page.getByRole('button', { name: /2026年10月2日/ }).click()
  await page.getByLabel('记录日期').click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '记录日期', exact: true })).toBeHidden()
  await expect(page.getByRole('dialog', { name: '添加事项', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '描述' }).fill('@网站计划')
  await page.getByRole('option', { name: /设计首页/ }).click()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('entry-editor.png'), animations: 'disabled' })
  await page.getByRole('dialog').getByRole('button', { name: '添加事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.entry-title')).toHaveText('整理设计灵感')

  const projectNav = page.getByRole('navigation', { name: '项目筛选' })
  await projectNav.getByRole('button', { name: /^阅读计划/ }).click()
  await page.locator('.entry-description').getByRole('button', { name: '@设计首页', exact: true }).click()
  await expect(page.locator('.month-heading h2')).toHaveText('2026.9')
  await expect(projectNav.getByRole('button', { name: /^全部项目/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.entry-title')).toHaveText('设计首页')
  await expect(page.locator('.reference-chip.backlink')).toContainText('整理设计灵感')
  await page.getByRole('button', { name: '编辑事项 设计首页', exact: true }).click()
  await page.getByRole('textbox', { name: '事项标题' }).fill('首页设计定稿')
  await page.getByRole('checkbox', { name: '已完成', exact: true }).uncheck()
  await page.getByRole('textbox', { name: '描述' }).fill('@2026-10-02')
  await page.getByRole('option', { name: /整理设计灵感/ }).click()
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.entry-title')).toHaveText('首页设计定稿')
  await expect(page.locator('.entry-description button')).toHaveText('@整理设计灵感')
  await expect(page.locator('.reference-chip.backlink')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '标为完成：首页设计定稿', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await noOverflow(page)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('calendar.png'), fullPage: true, animations: 'disabled' })

  await page.reload()
  await expect(page.locator('.entry-title')).toHaveText('首页设计定稿')
  await expect(page.locator('.entry-description button')).toHaveText('@整理设计灵感')
  await expect(page.locator('.reference-chip.backlink')).toHaveCount(1)
  if (isMobile) await page.getByRole('button', { name: '月', exact: true }).click()
  await switchSpace(page, otherSpace.email)
  await expect(projectNav.getByRole('button', { name: /^网站计划/ })).toHaveCount(0)
  await expect(page.locator('.entry-card')).toHaveCount(0)
  await switchSpace(page, space.email)
  await expect(page.locator('.entry-title')).toHaveText('首页设计定稿')

  await page.getByRole('button', { name: '编辑事项 首页设计定稿', exact: true }).click()
  await page.getByRole('button', { name: '删除事项', exact: true }).click()
  await page.getByRole('button', { name: '确认删除事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.getByRole('button', { name: '下个月', exact: true }).click()
  await page.getByRole('button', { name: '选择 2026-10-02', exact: true }).click()
  await expect(page.locator('.entry-title')).toHaveText('整理设计灵感')
  await expect(page.locator('.reference-chip')).toHaveCount(0)
  await expect(page.locator('.entry-mention.missing')).toHaveText('@设计首页（已删除）')
  await editSidebarProject(page, '阅读计划')
  await page.getByRole('button', { name: '删除项目', exact: true }).click()
  await expect(page.locator('.delete-confirm')).toContainText('1 个事项')
  await page.getByRole('button', { name: '确认删除项目', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.entry-card')).toHaveCount(0)
  await expect(projectNav.getByRole('button', { name: /^阅读计划/ })).toHaveCount(0)
  expect((await space.agenda()).entries).toEqual([])
  expect(errors).toEqual([])
  expect(apiRequests.length).toBeGreaterThan(0)
  for (const request of apiRequests) {
    expect(new URL(request.url()).origin).toBe(new URL(baseURL!).origin)
    expect(request.method()).not.toBe('OPTIONS')
    expect(await request.headerValue('cookie')).toContain('agenda-test-session=same-origin')
  }
})

test('流式日视图支持日期导航、筛选、编辑和跨月引用', async ({ page, space }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('日视图项目')
  const other = await space.project('关联项目')
  const target = await space.entry(other.id, '上月的准备', '2026-08-31')
  await space.entry(project.id, '今天的进展', '2026-09-13', [target])
  await space.entry(other.id, '另一项目事项', '2026-09-13')
  await enter(page, space.email)
  await page.getByRole('button', { name: '日', exact: true }).click()
  await expect(page.getByRole('button', { name: '日', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('group', { name: '月日历' })).toHaveCount(0)
  await expect(page.locator('.entry-card')).toHaveCount(2)
  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: /^日视图项目/ }).click()
  await expect(page.locator('.entry-title')).toHaveText('今天的进展')
  await page.getByRole('button', { name: '标为完成：今天的进展', exact: true }).click()
  await expect(page.getByRole('button', { name: '标为未完成：今天的进展', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '编辑事项 今天的进展', exact: true }).click()
  await page.getByRole('textbox', { name: '事项标题' }).fill('今天的进展已更新')
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await page.locator('.reference-chip').filter({ hasText: '上月的准备' }).click()
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-08-31')
  await expect(page.locator('.entry-title')).toHaveText('上月的准备')
  await expect(page.getByRole('button', { name: /^全部项目/ })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '后一天', exact: true }).click()
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-09-01')
  await expect(page.locator('.day-empty')).toContainText('当天暂无事项')
  await page.locator('.add-main').click()
  await expect(page.getByLabel('记录日期')).toHaveText('2026-09-01')
  await page.getByRole('textbox', { name: '事项标题' }).fill('九月第一笔')
  await page.getByRole('dialog').getByRole('button', { name: '添加事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.locator('.entry-title')).toHaveText('九月第一笔')
  await page.getByRole('button', { name: '前一天', exact: true }).click()
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-08-31')
  await page.getByLabel('日视图日期').click()
  await page.getByRole('button', { name: '去年', exact: true }).click({ clickCount: 2 })
  for (let i = 0; i < 6; i++) await page.getByRole('button', { name: '上个月', exact: true }).click()
  await page.getByRole('button', { name: /2024年2月28日/ }).click()
  await expect(page.getByRole('dialog', { name: '日视图日期', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '后一天', exact: true }).click()
  await expect(page.getByLabel('日视图日期')).toHaveText('2024-02-29')
  await page.getByRole('button', { name: '今天', exact: true }).click()
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-09-13')
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('day-view.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.locator('[data-date="2026-09-13"]')).toHaveClass(/is-selected/)
  await expect(page.locator('.entry-card')).toHaveCount(2)
})

test('周视图七日纵列、跨年导航与桌面悬浮/手机点击详情', async ({ page, space, isMobile }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-12-31T04:00:00Z'))
  const project = await space.project('周视图项目')
  const other = await space.project('其他项目')
  await space.entry(project.id, '周一计划', '2026-12-28')
  const todayEntry = await space.entry(project.id, '跨年准备', '2026-12-31', [], '**准备内容**')
  await space.entry(project.id, '同日第二事项', '2026-12-31')
  await space.entry(other.id, '其他项目事项', '2026-12-31')
  const completed = await space.entry(project.id, '周日总结', '2027-01-03')
  await space.api.patch(`/api/entries/${completed}`, { data: { completed: true } })
  await space.entry(project.id, '下周事项', '2027-01-07')
  await enter(page, space.email)
  await expect(page.getByRole('button', { name: isMobile ? '周' : '月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  if (!isMobile) await page.getByRole('button', { name: '周', exact: true }).click()
  const week = page.getByRole('group', { name: '周日历' })
  await expect(week.locator('.week-row')).toHaveCount(7)
  await expect(week.locator('.week-row').first()).toHaveAttribute('data-date', '2026-12-28')
  await expect(week.locator('.week-row').last()).toHaveAttribute('data-date', '2027-01-03')
  await expect(page.locator('.month-heading h2')).toHaveText('2026.12.28–2027.1.3')
  await expect(page.getByLabel('本周概览')).toHaveText(/总数\s*5\s*\/\s*未完成\s*4/)
  await expect(week.locator('[data-date="2026-12-31"]')).toHaveClass(/is-today/)
  await expect(week.locator('[data-date="2026-12-31"]')).toHaveClass(/is-selected/)
  await expect(week.locator('[data-date="2026-12-31"] .week-entry')).toHaveCount(3)
  await expect(week.locator('[data-date="2027-01-03"] .week-entry')).toHaveClass(/completed/)
  const item = week.locator('[data-date="2026-12-31"] .week-entry').first()
  if (isMobile) {
    await item.click()
    await expect(page.locator('.calendar-tooltip')).toBeVisible()
    await expect(page.locator('.calendar-tooltip-title')).toHaveText('跨年准备')
    await expect(page.locator('.calendar-tooltip .entry-description strong')).toHaveText('准备内容')
    await expect(page.getByRole('dialog', { name: '编辑事项' })).toHaveCount(0)
    await page.keyboard.press('Escape')
  } else {
    await item.hover()
    await expect(page.locator('.calendar-tooltip')).toContainText('跨年准备')
    await item.click()
    await expect(page.getByRole('dialog', { name: '编辑事项' })).toBeVisible()
    await page.getByRole('button', { name: '取消', exact: true }).click()
  }
  await week.locator('[data-date="2026-12-29"] .week-add').click()
  await expect(page.getByLabel('记录日期')).toHaveText('2026-12-29')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await week.locator('[data-date="2027-01-03"] .week-date').click()
  await expect(page.locator('.entry-title')).toHaveText('周日总结')
  if (isMobile) {
    await page.getByRole('button', { name: '编辑事项 周日总结' }).click()
    await expect(page.getByRole('dialog', { name: '编辑事项' })).toBeVisible()
    await page.getByRole('button', { name: '取消', exact: true }).click()
  }
  await page.getByRole('button', { name: '后一周' }).click()
  await expect(page.locator('.month-heading h2')).toHaveText('2027.1.4–2027.1.10')
  await expect(week.locator('.week-row').first()).toHaveAttribute('data-date', '2027-01-04')
  await expect(week.locator('[data-date="2027-01-10"]')).toHaveClass(/is-selected/)
  await expect(page.getByLabel('本周概览')).toHaveText(/总数\s*1\s*\/\s*未完成\s*1/)
  await page.getByRole('button', { name: '前一周' }).click()
  await expect(week.locator('[data-date="2027-01-03"]')).toHaveClass(/is-selected/)
  await page.getByRole('button', { name: '今天', exact: true }).click()
  await expect(page.getByLabel('周视图日期')).toHaveText('2026-12-31')
  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: /^周视图项目/ }).click()
  await expect(page.getByLabel('本周概览')).toHaveText(/总数\s*4\s*\/\s*未完成\s*3/)
  await expect(week.locator('.week-entry').filter({ hasText: '其他项目事项' })).toHaveCount(0)
  await page.getByRole('navigation', { name: '项目筛选' }).getByRole('button', { name: /^全部项目/ }).click()
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.getByRole('group', { name: '月日历' })).toBeVisible()
  await page.getByRole('button', { name: '周', exact: true }).click()
  await expect(week.locator('.week-row')).toHaveCount(7)
  await page.getByRole('combobox', { name: '工作台视图' }).click()
  await page.getByRole('option', { name: '项目总览', exact: true }).click()
  await page.getByRole('combobox', { name: '工作台视图' }).click()
  await page.getByRole('option', { name: '项目日历', exact: true }).click()
  await expect(page.getByRole('button', { name: '周', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator(`#entry-${todayEntry}`)).toBeVisible()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('week-view.png'), fullPage: true, animations: 'disabled' })
  await page.reload()
  await expect(page.getByRole('button', { name: isMobile ? '周' : '月', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('手机周视图长标题详情保持在可视区域内', async ({ page, space, isMobile }) => {
  test.skip(!isMobile)
  await page.clock.setFixedTime(new Date('2026-12-31T04:00:00Z'))
  await page.setViewportSize({ width: 320, height: 568 })
  const project = await space.project('长标题项目')
  const title = '需要完整查看的较长事项标题'.repeat(13)
  await space.entry(project.id, title, '2026-12-28', [], '详细内容'.repeat(700))
  await space.entry(project.id, title, '2027-01-03', [], '详细内容'.repeat(700))
  await enter(page, space.email)
  for (const date of ['2026-12-28', '2027-01-03']) {
    await page.getByRole('group', { name: '周日历' }).locator(`[data-date="${date}"] .week-entry`).click()
    const preview = page.locator('.calendar-tooltip')
    await expect(preview.locator('.calendar-tooltip-title')).toHaveText(title)
    await expect.poll(async () => preview.evaluate(element => {
      const box = element.getBoundingClientRect()
      const heading = element.querySelector('.calendar-tooltip-title')!.getBoundingClientRect()
      return box.top >= 0 && box.bottom <= window.innerHeight && heading.top >= 0 && element.scrollTop === 0 && element.scrollHeight > element.clientHeight
    })).toBe(true)
    await preview.evaluate(element => { element.scrollTop = element.scrollHeight })
    await expect.poll(async () => preview.evaluate(element => element.scrollTop > 0)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(preview).toBeHidden()
  }
  await noOverflow(page)
})

test('项目总览分组、无日期事项管理、筛选保留与跨视图引用', async ({ page, space, isMobile }, testInfo) => {
  test.setTimeout(60_000)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  // Let time advance: Vue's event timestamp guard must distinguish reopened popup listeners.
  await page.clock.install({ time: new Date('2026-09-13T04:00:00Z') })
  const project = await space.project('网站计划')
  const reading = await space.project('阅读计划')
  const empty = await space.project('待启动项目')
  const target = await space.entry(reading.id, '待整理的灵感', null, [], '先收集灵感，日期之后再安排。')
  const source = await space.entry(project.id, '当天记录', '2026-09-13', [target], serializeMention({ id: target, title: '待整理的灵感' }))
  await space.entry(project.id, '上月的准备', '2026-08-01')
  const completed = await space.entry(project.id, '已完成的想法', null)
  await space.api.patch(`/api/entries/${completed}`, { data: { completed: true } })
  const undated = await space.entry(project.id, '尚未安排的想法', null, [completed], serializeMention({ id: completed, title: '已完成的想法' }))
  await enter(page, space.email)
  const view = page.getByRole('combobox', { name: '工作台视图' })
  async function switchView(label: '项目日历' | '项目总览') {
    await view.click()
    await page.getByRole('option', { name: label, exact: true }).click()
    await expect(view).toContainText(label)
    await expect(view).toHaveAttribute('aria-expanded', 'false')
  }
  const nav = page.getByRole('navigation', { name: '项目筛选' })
  // Selecting a weekday or weekend cell only adds its border.
  if (isMobile) await page.getByRole('button', { name: '月', exact: true }).click()
  for (const date of ['2026-09-14', '2026-09-12']) {
    const day = page.locator(`[data-date="${date}"]`)
    const background = await day.evaluate(element => getComputedStyle(element).backgroundColor)
    await day.getByRole('button', { name: `选择 ${date}`, exact: true }).click()
    await expect(day).toHaveCSS('background-color', background)
    await expect(day).toHaveCSS('box-shadow', 'rgb(233, 179, 204) 0px 0px 0px 1px inset')
  }
  await page.getByRole('button', { name: '今天', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('calendar-selection-border.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: '日', exact: true }).click()
  await nav.getByRole('button', { name: /^网站计划/ }).click()
  await expect(page.locator('.summary-counts')).toHaveText(/总数\s*1\s*\/\s*未完成\s*1/)
  await nav.getByRole('button', { name: /^阅读计划/ }).click()
  const projectActions = nav.getByRole('button', { name: '项目操作 网站计划', exact: true })
  await projectActions.click()
  await expect(page.getByRole('menuitem')).toHaveText(['转到总览', '编辑', '↑上移', '↓下移'])
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('project-actions.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).toBeHidden()
  await expect(projectActions).toBeFocused()
  await expect(nav.getByRole('button', { name: /^阅读计划/ })).toHaveAttribute('aria-pressed', 'true')
  await projectActions.click()
  await page.getByRole('menuitem', { name: '转到总览', exact: true }).click()
  await expect(view).toContainText('项目总览')
  await expect(page.locator('.overview-project')).toHaveCount(1)
  await expect(page.getByRole('region', { name: '网站计划', exact: true })).toBeVisible()
  await expect(nav.getByRole('button', { name: /^网站计划/ })).toHaveAttribute('aria-pressed', 'true')
  await switchView('项目日历')
  await view.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('listbox')).toBeVisible()
  await expect(page.getByRole('option', { name: '项目日历', exact: true })).toHaveAttribute('data-state', 'checked')
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('workspace-view-select.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('listbox')).toBeHidden()
  await expect(view).toBeFocused()
  await expect(view).toContainText('项目日历')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: '项目日历', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  expect(errors).toEqual([])
  await expect(page.getByRole('option', { name: '项目总览', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(view).toContainText('项目总览')
  await expect(page.locator('.overview-project')).toHaveCount(1)
  const showCompleted = page.getByRole('button', { name: /^已完成\s*\d+$/ })
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.summary-counts')).toHaveText(/未完成\s*3\s*\/\s*已完成\s*1/)
  await expect(page.locator('.entry-title')).toHaveText(['尚未安排的想法', '上月的准备', '当天记录'])
  const sourceCreatedAt = (await space.agenda()).entries.find(entry => entry.id === source)!.createdAt
  const sourceCreatedDate = await page.evaluate(value => new Date(value).toLocaleDateString('sv-SE'), sourceCreatedAt)
  await expect(page.locator(`#entry-${source} .entry-created`)).toHaveAttribute('datetime', sourceCreatedAt)
  await expect(page.locator(`#entry-${source} .entry-created`)).toHaveText(`添加于 ${sourceCreatedDate}`)
  await showCompleted.focus()
  await page.keyboard.press('Space')
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'true')
  await expect(showCompleted).toHaveCSS('color', 'rgb(190, 79, 131)')
  await expect(showCompleted.locator('strong')).toHaveCSS('color', 'rgb(190, 79, 131)')
  await expect(page.locator('.summary-counts')).toHaveText(/未完成\s*3\s*\/\s*已完成\s*1/)
  await expect(page.locator('.entry-title')).toHaveText(['已完成的想法', '尚未安排的想法', '上月的准备', '当天记录'])
  await showCompleted.click()
  await expect(page.locator(`#entry-${completed}`)).toHaveCount(0)
  await page.locator(`#entry-${undated} .entry-description button`).click()
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator(`#entry-${completed}`)).toBeFocused()
  await showCompleted.click()
  await page.getByRole('button', { name: '标为完成：尚未安排的想法', exact: true }).click()
  await expect(page.locator(`#entry-${undated}`)).toHaveCount(0)
  await expect(page.locator(`#entry-${source}`)).toBeVisible()
  await showCompleted.click()
  await page.getByRole('button', { name: '标为未完成：尚未安排的想法', exact: true }).click()
  await expect(page.getByRole('button', { name: '标为完成：尚未安排的想法', exact: true })).toBeEnabled()
  await showCompleted.click()
  await expect(page.locator('.summary-counts')).toHaveText(/未完成\s*3\s*\/\s*已完成\s*1/)
  await nav.getByRole('button', { name: /^全部项目/ }).click()
  await expect(page.locator('.overview-project')).toHaveCount(3)
  await nav.getByRole('button', { name: /^网站计划/ }).click()
  await switchView('项目日历')
  await expect(page.getByRole('button', { name: '日', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-09-13')
  await expect(nav.getByRole('button', { name: /^网站计划/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator(`#entry-${source} .entry-created`)).toHaveText(`添加于 ${sourceCreatedDate}`)

  const mention = page.locator(`#entry-${source} .entry-description button`)
  if (!isMobile) {
    await mention.hover()
    await expect(page.locator('.calendar-tooltip:visible')).toContainText('未设日期')
  }
  await mention.click()
  await expect(view).toContainText('项目总览')
  await expect(nav.getByRole('button', { name: /^全部项目/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator(`#entry-${target}`)).toBeFocused()
  await expect(page.locator('.overview-project')).toHaveCount(3)
  await expect(page.getByRole('region', { name: '待启动项目', exact: true })).toContainText('暂无事项')
  await page.locator(`#entry-${target} .backlink`).click()
  await expect(view).toContainText('项目总览')
  await expect(page.locator(`#entry-${source}`)).toBeFocused()

  await page.getByRole('button', { name: '为 待启动项目 添加事项', exact: true }).click()
  await expect(page.getByLabel('所属项目')).toHaveValue(empty.id)
  await expect(page.getByRole('checkbox', { name: '不设日期', exact: true })).toBeChecked()
  await expect(page.getByRole('button', { name: '记录日期', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: '事项标题' }).fill('新的无日期事项')
  await page.getByRole('textbox', { name: '描述' }).fill('@未设日期')
  await expect(page.getByRole('listbox').getByRole('option', { name: /待整理的灵感/ })).toContainText('未设日期')
  await page.getByRole('listbox').getByRole('option', { name: /待整理的灵感/ }).click()
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('undated-editor.png'), animations: 'disabled' })
  await page.getByRole('dialog').getByRole('button', { name: '添加事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  const created = (await space.agenda()).entries.find(entry => entry.title === '新的无日期事项')!
  expect(created).toMatchObject({ date: null, projectId: empty.id, references: [target] })
  await page.getByRole('button', { name: '标为完成：新的无日期事项', exact: true }).click()
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('region', { name: '待启动项目', exact: true })).toHaveCount(0)
  await showCompleted.click()
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: '标为未完成：新的无日期事项', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '编辑事项 新的无日期事项', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: '不设日期', exact: true })).toBeChecked()
  await page.getByRole('checkbox', { name: '不设日期', exact: true }).uncheck()
  await page.getByRole('button', { name: '记录日期', exact: true }).click()
  await page.getByRole('button', { name: /2026年9月14日/ }).click()
  await expect(page.getByRole('dialog', { name: '记录日期', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  expect((await space.agenda()).entries.find(entry => entry.id === created.id)).toMatchObject({ date: '2026-09-14', completed: true, references: [target] })
  await switchView('项目日历')
  await expect(page.getByLabel('日视图日期')).toHaveText('2026-09-13')
  await expect(page.locator('.summary-counts')).toHaveText(/总数\s*2\s*\/\s*未完成\s*1/)
  await page.getByRole('button', { name: '后一天', exact: true }).click()
  await expect(page.locator('.entry-title')).toHaveText('新的无日期事项')
  await page.getByRole('button', { name: '编辑事项 新的无日期事项', exact: true }).click()
  await page.getByRole('checkbox', { name: '不设日期', exact: true }).check()
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(view).toContainText('项目总览')
  await expect(page.locator(`#entry-${created.id}`)).toContainText('未设日期')
  await switchView('项目日历')
  await expect(page.locator('.entry-card')).toHaveCount(0)
  await page.getByRole('button', { name: '月', exact: true }).click()
  await expect(page.locator('.calendar-entry').filter({ hasText: '尚未安排的想法' })).toHaveCount(0)
  await expect(page.locator('.summary-counts')).toHaveText(/总数\s*1\s*\/\s*未完成\s*1/)

  await page.reload()
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
  await switchView('项目总览')
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator(`#entry-${created.id}`)).toHaveCount(0)
  await showCompleted.click()
  await expect(page.locator(`#entry-${created.id}`)).toBeVisible()
  await showCompleted.click()
  // Following a reference reveals a completed project and still focuses its target.
  await page.locator(`#entry-${target} .backlink`).filter({ hasText: '新的无日期事项' }).click()
  await expect(showCompleted).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator(`#entry-${created.id}`)).toBeFocused()
  await expect(page.locator(`#entry-${created.id}`)).toContainText('未设日期')
  await expect(page.locator(`#entry-${undated}`)).toContainText('未设日期')
  await noOverflow(page)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('project-overview.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('region', { name: '待启动项目', exact: true }).getByRole('button', { name: '编辑项目 待启动项目', exact: true }).click()
  await page.getByRole('textbox', { name: '项目名称' }).fill('总览中改名的项目')
  await page.getByRole('button', { name: '保存项目', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('region', { name: '总览中改名的项目', exact: true })).toContainText('新的无日期事项')
  await page.getByRole('button', { name: '编辑事项 新的无日期事项', exact: true }).click()
  await page.getByRole('button', { name: '删除事项', exact: true }).click()
  await page.getByRole('button', { name: '确认删除事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(page.getByRole('region', { name: '总览中改名的项目', exact: true })).toContainText('暂无事项')
  await expect(page.locator(`#entry-${target} .backlink`)).toHaveText('@当天记录')
  expect(errors).toEqual([])
})

test('描述 Markdown 安全展示、@筛选与键盘中间插入、刷新及引用删除同步', async ({ page, space }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('描述项目')
  const other = await space.project('候选项目')
  const first = await space.entry(other.id, '相同标题', '2026-08-01')
  const second = await space.entry(other.id, '相同标题', '2026-10-02')
  await enter(page, space.email)
  await page.locator('.add-main').click()
  await page.getByRole('textbox', { name: '事项标题' }).fill('描述回归')
  await page.getByLabel('所属项目').selectOption(project.id)
  const description = page.getByRole('textbox', { name: '描述' })
  const options = page.getByRole('listbox', { name: '引用事项候选' }).getByRole('option')
  await description.fill('@候选项目')
  await expect(options).toHaveCount(2)
  const listId = await page.getByRole('listbox', { name: '引用事项候选' }).getAttribute('id')
  await expect(description).toHaveAttribute('aria-controls', listId!)
  await description.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: '添加事项', exact: true })).toBeVisible()
  await expect(description).toBeFocused()

  // Simulate the IME event contract: confirming Enter must not select or submit.
  await description.dispatchEvent('compositionstart')
  await description.fill('@相同')
  await description.dispatchEvent('keydown', { key: 'Enter', isComposing: true, keyCode: 229 })
  await expect(description).toHaveValue('@相同')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await description.dispatchEvent('compositionend')
  await expect(options).toHaveCount(2)
  await description.press('ArrowDown')
  await expect(options.nth(1)).toHaveAttribute('aria-selected', 'true')
  await expect(description).toHaveAttribute('aria-activedescendant', (await options.nth(1).getAttribute('id'))!)
  await description.press('ArrowUp')
  await expect(options.nth(0)).toHaveAttribute('aria-selected', 'true')
  await description.press('ArrowDown')
  await description.press('Enter')
  await expect(description).toHaveValue(serializeMention({ id: first, title: '相同标题' }))

  const literal = '  第一行 <img src=x onerror="window.__descriptionExecuted=true">\n<script>window.__descriptionExecuted=true</script>\n**粗体** [链接](javascript:alert(1)) 邮箱 a@example.com\n'
  const suffix = ' 后缀  \n最后一行  '
  await description.fill(`${literal}@候选项目 2026-10${suffix}`)
  const caret = literal.length + '@候选项目 2026-10'.length
  await description.evaluate((element, position) => {
    const input = element as HTMLTextAreaElement
    input.setSelectionRange(position, position)
    input.dispatchEvent(new Event('select', { bubbles: true }))
  }, caret)
  await expect(options).toHaveCount(1)
  await expect(options).toContainText('2026-10-02')
  await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('description-picker.png'), animations: 'disabled' })
  await description.press('Enter')
  const saved = `${literal}${serializeMention({ id: second, title: '相同标题' })}${suffix}`
  await expect(description).toHaveValue(saved)
  expect(await description.evaluate(element => (element as HTMLTextAreaElement).selectionStart)).toBe(literal.length + serializeMention({ id: second, title: '相同标题' }).length)
  await page.getByRole('dialog').getByRole('button', { name: '添加事项', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  const source = (await space.agenda()).entries.find(entry => entry.title === '描述回归')!
  expect(source).toMatchObject({ description: saved, references: [second] })
  await page.reload()
  const rendered = page.locator('.entry-card .entry-description')
  await expect(rendered).toContainText('第一行 <img src=x onerror="window.__descriptionExecuted=true">')
  await expect(rendered).toContainText('<script>window.__descriptionExecuted=true</script>')
  await expect(rendered.locator('strong')).toHaveText('粗体')
  await expect(rendered.locator('a, img, script')).toHaveCount(0)
  await expect(rendered.locator('.entry-mention')).toHaveText('@相同标题')
  expect(await page.evaluate(() => '__descriptionExecuted' in window)).toBe(false)
  await noOverflow(page)
  expect(await rendered.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('description-detail.png'), fullPage: true, animations: 'disabled' })

  await page.getByRole('button', { name: '编辑事项 描述回归', exact: true }).click()
  await expect(description).toHaveValue(saved)
  await description.fill(literal + suffix)
  await page.getByRole('button', { name: '保存修改', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  expect((await space.agenda()).entries.find(entry => entry.id === source.id)?.references).toEqual([])
  await page.reload()
  await expect(page.locator('.entry-card .entry-mention')).toHaveCount(0)
})

test('基础 Markdown 在详情与悬浮卡片展示，编辑时保留源码与引用', async ({ page, space, isMobile }) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('Markdown 项目')
  const target = await space.entry(project.id, '引用目标', '2026-10-02')
  const mention = serializeMention({ id: target, title: '引用目标' })
  const source = [
    '# 标题',
    '正文 **加粗**、*斜体*、~~删除~~、`内联代码`，以及 [安全链接](https://example.com/path)。',
    '',
    '- 第一项',
    `- 第二项 ${mention}`,
    '',
    '> 引用段落',
    '',
    '```text',
    mention,
    '```',
    '[危险链接](javascript:alert(1)) <img src=x onerror="window.__descriptionExecuted=true">',
  ].join('\n')
  await space.entry(project.id, 'Markdown 事项', '2026-09-13', [target], source)
  await enter(page, space.email)
  const detail = page.locator('.entry-card .entry-description')
  await page.getByRole('button', { name: '显示全部' }).click()
  await expect(detail.locator('h1')).toHaveText('标题')
  await expect(detail.locator('strong')).toHaveText('加粗')
  await expect(detail.locator('em')).toHaveText('斜体')
  await expect(detail.locator('s')).toHaveText('删除')
  await expect(detail.locator('p code')).toHaveText('内联代码')
  await expect(detail.locator('a')).toHaveAttribute('href', 'https://example.com/path')
  await expect(detail.locator('li')).toHaveCount(2)
  await expect(detail.locator('blockquote')).toContainText('引用段落')
  await expect(detail.locator('pre code')).toHaveText(mention)
  await expect(detail.locator('button.entry-mention')).toHaveText('@引用目标')
  await expect(detail.locator('a')).toHaveCount(1)
  await expect(detail.locator('img, script')).toHaveCount(0)
  expect(await page.evaluate(() => '__descriptionExecuted' in window)).toBe(false)
  await noOverflow(page)
  if (!isMobile) {
    await page.locator('.calendar-entry').filter({ hasText: 'Markdown 事项' }).hover()
    const tooltip = page.locator('.calendar-tooltip').filter({ hasText: 'Markdown 事项' })
    await expect(tooltip.locator('h1')).toHaveText('标题')
    await expect(tooltip.locator('button.entry-mention')).toHaveCount(0)
  }
  await page.getByRole('button', { name: '编辑事项 Markdown 事项' }).click()
  await expect(page.getByRole('textbox', { name: '描述' })).toHaveValue(source)
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('combobox', { name: '工作台视图' }).click()
  await page.getByRole('option', { name: '项目总览', exact: true }).click()
  await expect(detail.locator('h1')).toHaveText('标题')
  await detail.locator('button.entry-mention').click()
  await expect(page.locator(`#entry-${target}`)).toBeVisible()
})

test('legacy 引用保留/移除/转为标记，目标改名删除后展示与再保存', async ({ page, space, isMobile }) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('旧数据兼容')
  const target = await space.entry(project.id, '旧标题', '2026-10-02')
  const removable = await space.entry(project.id, '可移除', '2026-10-03')
  const source = await space.entry(project.id, '旧引用来源', '2026-09-13', [target, removable])
  await enter(page, space.email)
  const reference = page.locator('.entry-card .reference-chip').filter({ hasText: '@旧标题' })
  const tooltip = page.locator('.calendar-tooltip')
  if (!isMobile) {
    await reference.hover()
    await expect(tooltip).toBeVisible()
    await expect(tooltip).toContainText('旧标题')
    await expect(tooltip).toContainText('2026-10-02')
    await expect(tooltip).toContainText('旧数据兼容')
    await expect(reference).not.toHaveAttribute('title')
  }
  await reference.click()
  const backlink = page.locator('.entry-card .backlink').filter({ hasText: '@旧引用来源' })
  await expect(backlink).toBeVisible()
  if (!isMobile) {
    await backlink.hover()
    await expect(tooltip).toBeVisible()
    await expect(tooltip).toContainText('旧引用来源')
    await expect(tooltip).toContainText('2026-09-13')
    await expect(backlink).not.toHaveAttribute('title')
  }
  await backlink.click()
  const edit = () => page.getByRole('button', { name: '编辑事项 旧引用来源', exact: true }).click()
  const save = async () => {
    await page.getByRole('button', { name: '保存修改', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
  }
  const current = async () => (await space.agenda()).entries.find(entry => entry.id === source)!
  await edit()
  await page.getByRole('textbox', { name: '描述' }).fill('新增纯文本，不丢旧引用')
  await save()
  expect((await current()).references).toEqual([target, removable].sort())
  await edit()
  await page.getByRole('button', { name: '移除引用 @可移除', exact: true }).click()
  await save()
  expect((await current()).references).toEqual([target])
  await edit()
  await page.getByRole('textbox', { name: '描述' }).fill('@旧标题')
  await page.getByRole('option', { name: /旧标题/ }).click()
  await expect(page.getByRole('button', { name: '移除引用 @旧标题', exact: true })).toHaveCount(0)
  // Removing a marker just converted from legacy must remove the relation as well.
  await page.getByRole('textbox', { name: '描述' }).fill('')
  await save()
  expect((await current()).references).toEqual([])
  await edit()
  await page.getByRole('textbox', { name: '描述' }).fill('@旧标题')
  await page.getByRole('option', { name: /旧标题/ }).click()
  await save()
  expect((await current()).references).toEqual([target])
  const targetEntry = (await space.agenda()).entries.find(entry => entry.id === target)!
  expect((await space.api.put(`/api/entries/${target}`, { data: { ...targetEntry, title: '改名后标题' } })).ok()).toBe(true)
  await page.reload()
  await expect(page.locator('.entry-card .entry-mention')).toHaveText('@改名后标题')
  if (!isMobile) {
    const mention = page.locator('.entry-card .entry-mention')
    await mention.hover()
    await expect(tooltip).toBeVisible()
    await expect(tooltip).toContainText('改名后标题')
    await expect(tooltip).toContainText('2026-10-02')
    await expect(tooltip.locator('button, a')).toHaveCount(0)
    await expect(mention).not.toHaveAttribute('title')
  }
  expect((await current()).description).toContain('@[旧标题]')
  expect((await space.api.delete(`/api/entries/${target}`)).ok()).toBe(true)
  await page.reload()
  await expect(page.locator('.entry-card .entry-mention.missing')).toHaveText('@旧标题（已删除）')
  await expect(page.locator('.entry-card button.entry-mention')).toHaveCount(0)
  await edit()
  await save()
  expect(await current()).toMatchObject({ description: serializeMention({ id: target, title: '旧标题' }), references: [] })
})

test('长描述详情不溢出，桌面 tooltip 悬停/键盘聚焦及 viewport 边界', async ({ page, space, isMobile }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-13T04:00:00Z'))
  const project = await space.project('长内容项目')
  const target = await space.entry(project.id, '引用目标', '2026-10-02')
  const description = `${serializeMention({ id: target, title: '引用目标' })}\n${'超长无空格文本'.repeat(160)}\n${'多行内容\n'.repeat(100)}`
  await space.entry(project.id, '长描述事项', '2026-09-13', [target], description)
  await enter(page, space.email)
  await expect(page.locator('.entry-card .entry-description')).toContainText('多行内容')
  const detail = page.locator('.entry-card .entry-description')
  const expand = page.getByRole('button', { name: '显示全部', exact: true })
  await expect(expand).toHaveAttribute('aria-expanded', 'false')
  expect(await detail.evaluate(element => element.clientHeight <= parseFloat(getComputedStyle(element).lineHeight) * 4 + 1 && element.scrollHeight > element.clientHeight)).toBe(true)
  await expand.click()
  const collapse = page.getByRole('button', { name: '收起', exact: true })
  await expect(collapse).toHaveAttribute('aria-expanded', 'true')
  expect(await detail.evaluate(element => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
  await collapse.click()
  await expect(expand).toHaveAttribute('aria-expanded', 'false')
  await noOverflow(page)
  expect(await page.locator('.entry-card .entry-description').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.getByRole('button', { name: '编辑事项 长描述事项', exact: true }).click()
  const editor = page.getByRole('textbox', { name: '描述' })
  await expect(editor).toHaveValue(description)
  await expect.poll(() => editor.evaluate(element => element.scrollHeight <= element.clientHeight + 1)).toBe(true)
  const dialogScroll = page.locator('.dialog-inner')
  expect(await dialogScroll.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
  await dialogScroll.evaluate(element => { element.scrollTop = 0 })
  const editorBounds = await editor.boundingBox()
  expect(editorBounds).not.toBeNull()
  await page.mouse.move(editorBounds!.x + 20, Math.max(editorBounds!.y + 20, 0))
  await page.mouse.wheel(0, 400)
  await expect.poll(() => dialogScroll.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await editor.fill('缩短描述')
  await expect.poll(() => editor.evaluate(element => element.clientHeight < 200)).toBe(true)
  await page.getByRole('button', { name: '关闭弹窗' }).click()
  if (isMobile) {
    await page.locator('.entry-card').evaluate(element => element.scrollIntoView({ block: 'start' }))
    await page.screenshot({ path: testInfo.outputPath('long-description-mobile.png'), animations: 'disabled' })
    return
  }
  const trigger = page.locator('.calendar-entry').filter({ hasText: '长描述事项' })
  await trigger.hover()
  const tooltip = page.locator('.calendar-tooltip').filter({ hasText: '长描述事项' })
  await expect(tooltip).toBeVisible()
  await expect(tooltip).toContainText('2026-09-13')
  await expect(tooltip).toContainText('长内容项目')
  await expect(tooltip).toContainText('进行中')
  await expect(tooltip).toContainText('@引用目标')
  await expect(tooltip.locator('button, a')).toHaveCount(0)
  expect(await tooltip.evaluate(element => !element.closest('.calendar-card'))).toBe(true)
  const bounds = await tooltip.boundingBox()
  const viewport = page.viewportSize()!
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height)
  expect(await tooltip.evaluate(element => element.scrollHeight > element.clientHeight && element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('description-tooltip.png'), animations: 'disabled' })
  await page.mouse.move(0, 0)
  await expect(tooltip).toBeHidden()
  // A real Tab focus (rather than programmatic focus after a pointer event).
  await page.getByRole('button', { name: '在 2026-09-13 添加事项', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(trigger).toBeFocused()
  await expect(tooltip).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-describedby', /.+/)
  await page.keyboard.press('Escape')
  await expect(tooltip).toBeHidden()
})

test('同步失败可重试，切换邮箱后迟到的旧响应不会覆盖新空间', async ({ page, space, otherSpace }) => {
  await space.project('旧空间项目')
  await otherSpace.project('新空间项目')
  await enter(page, space.email)
  await page.route('**/api/agenda', route => route.abort('failed'), { times: 1 })
  await page.locator('.sync-button').click()
  await expect(page.getByRole('alert')).toContainText('连接云端失败')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
  await expect(page.getByRole('alert')).toHaveCount(0)

  let release!: () => void
  let started!: () => void
  const gate = new Promise<void>(resolve => { release = resolve })
  const pending = new Promise<void>(resolve => { started = resolve })
  await page.route('**/api/agenda', async route => {
    if (route.request().headers()['x-user-email'] !== space.email) return route.continue()
    const response = await route.fetch()
    started()
    await gate
    await route.fulfill({ response })
  })
  await page.locator('.sync-button').click()
  await pending
  try {
    await switchSpace(page, otherSpace.email)
    await expect(page.getByRole('button', { name: /^新空间项目/ })).toBeVisible()
  } finally { release() }
  await expect(page.locator('.sync-button')).toContainText('已与云端同步')
  // Drain the old browser request before asserting the final rendered space.
  await page.waitForLoadState('networkidle')
  await expect(page.getByRole('button', { name: /^旧空间项目/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^新空间项目/ })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('agenda:email'))).toBe(otherSpace.email)
})
